-- Esquema v8.0, sin datos del equipo.
CREATE TABLE public.categorias_material (
    id integer NOT NULL,
    nombre character varying(60) NOT NULL,
    unidad_medida_default character varying(10) NOT NULL
);

ALTER TABLE public.categorias_material ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.documentos_verificacion (
    id bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_subida timestamp(6) without time zone NOT NULL,
    tipo character varying(10) NOT NULL,
    url_archivo character varying(255) NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE public.documentos_verificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_verificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.mensajes (
    id bigint NOT NULL,
    contenido text,
    fecha_envio timestamp(6) without time zone NOT NULL,
    fecha_lectura timestamp(6) without time zone,
    remitente_id bigint NOT NULL,
    solicitud_id bigint NOT NULL
);

ALTER TABLE public.mensajes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensajes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    leida boolean NOT NULL,
    mensaje character varying(255) NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.publicaciones_material (
    id bigint NOT NULL,
    cantidad numeric(8,2) NOT NULL,
    descripcion text,
    direccion character varying(255) NOT NULL,
    distrito character varying(80),
    estado character varying(20) NOT NULL,
    fecha_disponibilidad date,
    fecha_publicacion timestamp(6) without time zone NOT NULL,
    foto_url character varying(255),
    latitud numeric(10,7) NOT NULL,
    longitud numeric(10,7) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    categoria_material_id integer NOT NULL,
    generador_id bigint NOT NULL
);

ALTER TABLE public.publicaciones_material ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publicaciones_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.punto_reciclaje_materiales (
    punto_reciclaje_id bigint NOT NULL,
    categoria_material_id integer NOT NULL
);

CREATE TABLE public.puntos_reciclaje (
    id bigint NOT NULL,
    calificacion_promedio numeric(3,2),
    direccion character varying(255) NOT NULL,
    distrito character varying(80),
    horario_atencion character varying(120),
    latitud numeric(10,7) NOT NULL,
    longitud numeric(10,7) NOT NULL,
    nombre character varying(150) NOT NULL,
    tipo character varying(20) NOT NULL
);

ALTER TABLE public.puntos_reciclaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.puntos_reciclaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles (
    id integer NOT NULL,
    descripcion character varying(150),
    nombre character varying(40) NOT NULL
);

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ruta_paradas (
    orden integer NOT NULL,
    punto_reciclaje_id bigint NOT NULL,
    ruta_id bigint NOT NULL
);

CREATE TABLE public.rutas_recoleccion (
    id bigint NOT NULL,
    descripcion text,
    distancia_total_km numeric(6,2),
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_ruta date,
    nombre character varying(150) NOT NULL,
    tiempo_estimado_min integer,
    recolector_id bigint NOT NULL
);

ALTER TABLE public.rutas_recoleccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rutas_recoleccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.solicitudes_recoleccion (
    id bigint NOT NULL,
    calificacion_recolector integer,
    codigo_qr character varying(100),
    estado character varying(20) NOT NULL,
    fecha_coordinada timestamp(6) without time zone,
    fecha_ejecucion timestamp(6) without time zone,
    fecha_solicitud timestamp(6) without time zone NOT NULL,
    fecha_validacion timestamp(6) without time zone,
    metodo_pago character varying(20),
    monto_pago numeric(10,2),
    observaciones text,
    prioritaria boolean NOT NULL,
    qr_validado boolean NOT NULL,
    publicacion_id bigint NOT NULL,
    recolector_id bigint
);

ALTER TABLE public.solicitudes_recoleccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_recoleccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tickets_soporte (
    id bigint NOT NULL,
    asunto character varying(150) NOT NULL,
    categoria character varying(30) NOT NULL,
    descripcion text NOT NULL,
    estado character varying(10) NOT NULL,
    evidencia_url character varying(255),
    fecha_cierre timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    solicitud_id bigint,
    usuario_id bigint NOT NULL
);

ALTER TABLE public.tickets_soporte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_soporte_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    calificacion_promedio numeric(3,2),
    descripcion text,
    email character varying(150) NOT NULL,
    en_linea boolean NOT NULL,
    estado character varying(30) NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    foto_perfil_url character varying(255),
    metodo_pago_preferido character varying(20),
    nombre_completo character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    telefono character varying(20),
    rol_id integer NOT NULL
);

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.categorias_material
    ADD CONSTRAINT categorias_material_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documentos_verificacion
    ADD CONSTRAINT documentos_verificacion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT mensajes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.publicaciones_material
    ADD CONSTRAINT publicaciones_material_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.punto_reciclaje_materiales
    ADD CONSTRAINT punto_reciclaje_materiales_pkey PRIMARY KEY (punto_reciclaje_id, categoria_material_id);

ALTER TABLE ONLY public.puntos_reciclaje
    ADD CONSTRAINT puntos_reciclaje_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ruta_paradas
    ADD CONSTRAINT ruta_paradas_pkey PRIMARY KEY (punto_reciclaje_id, ruta_id);

ALTER TABLE ONLY public.rutas_recoleccion
    ADD CONSTRAINT rutas_recoleccion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.solicitudes_recoleccion
    ADD CONSTRAINT solicitudes_recoleccion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tickets_soporte
    ADD CONSTRAINT tickets_soporte_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categorias_material
    ADD CONSTRAINT ukdo4klo9dk30cmyc2x263lcgqt UNIQUE (nombre);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukldv0v52e0udsh2h1rs0r0gw1n UNIQUE (nombre);

ALTER TABLE ONLY public.ruta_paradas
    ADD CONSTRAINT ukqu72j7nloye2k4xjwt5deg16k UNIQUE (ruta_id, orden);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

CREATE INDEX idx_publicaciones_mapa ON public.publicaciones_material USING btree (estado, distrito);

ALTER TABLE ONLY public.solicitudes_recoleccion
    ADD CONSTRAINT fk1hcekiu819661dtp34qe6e514 FOREIGN KEY (publicacion_id) REFERENCES public.publicaciones_material(id);

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk1mxbjb81ft61gwlh0kabubndc FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.tickets_soporte
    ADD CONSTRAINT fk55acvo3k2l1gakst41c34fog FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.documentos_verificacion
    ADD CONSTRAINT fkal022o0vme5m2udabtw4smuxk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.ruta_paradas
    ADD CONSTRAINT fkd42q628kq4nnicxayu00av349 FOREIGN KEY (ruta_id) REFERENCES public.rutas_recoleccion(id);

ALTER TABLE ONLY public.solicitudes_recoleccion
    ADD CONSTRAINT fkfq61chywaw6okf6jn2p620srx FOREIGN KEY (recolector_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fklfsfnt3bahk64b9mjwy04eqx4 FOREIGN KEY (remitente_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fkmqfbx9jttkd138kupuf8yhj0 FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_recoleccion(id);

ALTER TABLE ONLY public.publicaciones_material
    ADD CONSTRAINT fkohjo1dikjn63tbue4ergm69hx FOREIGN KEY (categoria_material_id) REFERENCES public.categorias_material(id);

ALTER TABLE ONLY public.punto_reciclaje_materiales
    ADD CONSTRAINT fkp6ms8vrd2oqw17tk9645ei0in FOREIGN KEY (punto_reciclaje_id) REFERENCES public.puntos_reciclaje(id);

ALTER TABLE ONLY public.publicaciones_material
    ADD CONSTRAINT fkpcquxwysx18wtkrjjf4jugg5n FOREIGN KEY (generador_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fkqf5elo4jcq7qrt83oi0qmenjo FOREIGN KEY (rol_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.tickets_soporte
    ADD CONSTRAINT fkqjqlcfump95xxnpu17b70sew5 FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_recoleccion(id);

ALTER TABLE ONLY public.punto_reciclaje_materiales
    ADD CONSTRAINT fkqs7i0w316cxt0iyl4lj58dqmc FOREIGN KEY (categoria_material_id) REFERENCES public.categorias_material(id);

ALTER TABLE ONLY public.rutas_recoleccion
    ADD CONSTRAINT fkrkgvegctes8mdlj3v3vm7j7b3 FOREIGN KEY (recolector_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.ruta_paradas
    ADD CONSTRAINT fksbb63w9tiafk6jfavb1w3cu1i FOREIGN KEY (punto_reciclaje_id) REFERENCES public.puntos_reciclaje(id);

-- Datos ficticios: ids altos para distinguirlos de los datos DEMO del arranque.
INSERT INTO roles(id,nombre,descripcion) VALUES (1,'generador','Generador'),(2,'recolector','Recolector');
INSERT INTO categorias_material(id,nombre,unidad_medida_default) VALUES (1,'cartón','kg'),(2,'PET','kg');
INSERT INTO usuarios(id,nombre_completo,email,password_hash,telefono,metodo_pago_preferido,en_linea,
    calificacion_promedio,estado,fecha_registro,rol_id)
VALUES (101,'Usuario anterior','legacy@qhurinet.test','hash-legacy','987654321','yape',true,0,'activo','2026-09-29 12:00:00',1),
    (102,'Recolector anterior','recolector-legacy@qhurinet.test','hash-recolector','912345678','efectivo',true,0,'activo','2026-09-29 12:00:00',2);
INSERT INTO publicaciones_material(id,cantidad,descripcion,direccion,distrito,estado,fecha_disponibilidad,
    fecha_publicacion,latitud,longitud,unidad_medida,categoria_material_id,generador_id)
VALUES (501,7.50,'Material anterior','Direccion anterior','Lima','reservado','2026-10-10','2026-09-29 12:00:00',
    -12.05,-77.04,'kg',1,101);
INSERT INTO solicitudes_recoleccion(id,codigo_qr,estado,fecha_solicitud,prioritaria,qr_validado,publicacion_id,recolector_id)
VALUES (601,'QR_PREVIO','creada','2026-09-29 13:00:00',false,false,501,102);

-- Cambios del cierre v8.0 (16 tablas) y datos ficticios que deben trasladarse.
ALTER TABLE usuarios ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE publicaciones_material ADD COLUMN franja_horaria varchar(20), ADD COLUMN monto_pago numeric(10,2),
    ADD COLUMN metodo_pago varchar(20), ADD COLUMN motivo_cancelacion varchar(500);
ALTER TABLE solicitudes_recoleccion ADD COLUMN franja_horaria varchar(20), ADD COLUMN comentario_calificacion varchar(200);
ALTER TABLE puntos_reciclaje ADD COLUMN activo boolean NOT NULL DEFAULT true;
CREATE TABLE identidades_externas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id bigint NOT NULL REFERENCES usuarios(id),
    proveedor varchar(20) NOT NULL, identificador varchar(255) NOT NULL, UNIQUE(proveedor,identificador));
CREATE TABLE metodos_pago_usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id bigint NOT NULL REFERENCES usuarios(id),
    tipo varchar(20) NOT NULL, dato varchar(34), predeterminado boolean NOT NULL);
CREATE TABLE usuarios_materiales (
    usuario_id bigint NOT NULL REFERENCES usuarios(id), categoria_material_id int NOT NULL REFERENCES categorias_material(id),
    PRIMARY KEY(usuario_id,categoria_material_id));
INSERT INTO usuarios(id,nombre_completo,email,password_hash,telefono,en_linea,calificacion_promedio,estado,fecha_registro,rol_id)
VALUES (103,'Federado anterior','federado@qhurinet.test',null,'987654321',true,0,'activo','2026-09-29 12:00:00',1);
INSERT INTO identidades_externas(id,usuario_id,proveedor,identificador)
VALUES (1,101,'google','legacy-google'),(2,101,'facebook','legacy-facebook'),(3,103,'google','solo-google');
INSERT INTO metodos_pago_usuario(id,usuario_id,tipo,dato,predeterminado)
VALUES (11,101,'yape','987654321',true),(12,101,'tarjeta','1234',false),(13,101,'plin','912345678',false),
    (14,101,'transferencia','12345678901234567890',false),(15,101,'efectivo',null,false);
INSERT INTO usuarios_materiales(usuario_id,categoria_material_id) VALUES (101,2),(101,1);
UPDATE publicaciones_material SET franja_horaria='manana',monto_pago=15,metodo_pago='yape' WHERE id=501;
UPDATE solicitudes_recoleccion SET franja_horaria='tarde',comentario_calificacion='Comentario previo' WHERE id=601;
