-- Evolucion aditiva y repetible; se ejecuta despues de Hibernate. Sin borrar datos.
ALTER TABLE usuarios ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE publicaciones_material ADD COLUMN IF NOT EXISTS franja_horaria varchar(20);
ALTER TABLE publicaciones_material ADD COLUMN IF NOT EXISTS monto_pago numeric(10,2);
ALTER TABLE publicaciones_material ADD COLUMN IF NOT EXISTS metodo_pago varchar(20);
ALTER TABLE publicaciones_material ADD COLUMN IF NOT EXISTS motivo_cancelacion varchar(500);
ALTER TABLE solicitudes_recoleccion ADD COLUMN IF NOT EXISTS franja_horaria varchar(20);
ALTER TABLE solicitudes_recoleccion ADD COLUMN IF NOT EXISTS comentario_calificacion varchar(200);
ALTER TABLE puntos_reciclaje ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS usuarios_materiales (
 usuario_id bigint NOT NULL REFERENCES usuarios(id), categoria_material_id integer NOT NULL REFERENCES categorias_material(id),
 PRIMARY KEY(usuario_id,categoria_material_id));
CREATE TABLE IF NOT EXISTS metodos_pago_usuario (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id bigint NOT NULL REFERENCES usuarios(id),
 tipo varchar(20) NOT NULL, dato varchar(34), predeterminado boolean NOT NULL);
CREATE TABLE IF NOT EXISTS identidades_externas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id bigint NOT NULL REFERENCES usuarios(id),
 proveedor varchar(20) NOT NULL, identificador varchar(255) NOT NULL, UNIQUE(proveedor,identificador));
-- Preservar preferencias previas sin inventar numeros de billetera, cuenta o tarjeta.
INSERT INTO metodos_pago_usuario(usuario_id,tipo,dato,predeterminado)
 SELECT u.id,u.metodo_pago_preferido,null,true FROM usuarios u
 WHERE u.metodo_pago_preferido IS NOT NULL AND NOT EXISTS (SELECT 1 FROM metodos_pago_usuario m WHERE m.usuario_id=u.id);
-- Conservar archivos existentes: cambia solo la referencia, no se mueven los archivos.
UPDATE usuarios SET foto_perfil_url = regexp_replace(foto_perfil_url, '^uploads/fotos_perfil/', '/api/v1/files/fotos_perfil--')
 WHERE foto_perfil_url LIKE 'uploads/fotos_perfil/%';
UPDATE publicaciones_material SET foto_url = regexp_replace(foto_url, '^uploads/fotos_publicaciones/', '/api/v1/files/fotos_publicaciones--')
 WHERE foto_url LIKE 'uploads/fotos_publicaciones/%';
UPDATE documentos_verificacion SET url_archivo = regexp_replace(url_archivo, '^uploads/documentos_verificacion/', '/api/v1/files/documentos_verificacion--')
 WHERE url_archivo LIKE 'uploads/documentos_verificacion/%';
UPDATE tickets_soporte SET evidencia_url = regexp_replace(evidencia_url, '^uploads/evidencias_tickets/', '/api/v1/files/evidencias_tickets--')
 WHERE evidencia_url LIKE 'uploads/evidencias_tickets/%';
